FROM python:3.7.8-buster

COPY ./app/requirements.txt /srv/python-sample-app/requirements.txt

RUN pip3 install -r /srv/python-sample-app/requirements.txt --no-cache-dir

COPY ./app /srv/python-sample-app
WORKDIR /srv/python-sample-app/
EXPOSE 5000
CMD sleep 10 && flask db upgrade &&\
    uwsgi --ini wsgi_settings.ini